apiVersion: apps/v1
kind: Deployment
metadata:
  name: jiya-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jiya
  template:
    metadata:
      labels:
        app: jiya
    spec:
      containers:
      - name: app
        image: jiya2022/app:latest
        ports:
        - containerPort: 3000
